language: smalltalk
sudo: false

os:
  - osx
  - linux

smalltalk:
  - Pharo-7.0
  - Pharo64-7.0
  
smalltalk_config:
  - .engine.smalltalk.ston
  - .smalltalk.ston

branches:
  only:
    - master

smalltalk_edge:
  source: feenkcom/smalltalkCI
  branch: master
