language: smalltalk
sudo: false

os:
  - osx
  - linux

smalltalk:
  - Pharo-6.1
  - Pharo64-6.1
  
smalltalk_config:
  - .engine.smalltalk.ston
  - .smalltalk.ston

branches:
  only:
    - pharo6

smalltalk_edge:
  source: feenkcom/smalltalkCI
  branch: master
